//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplicationTema2.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebServiceTema2Soap")]
    public interface WebServiceTema2Soap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        WindowsFormsApplicationTema2.ServiceReference1.HelloWorldResponse HelloWorld(WindowsFormsApplicationTema2.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApplicationTema2.ServiceReference1.HelloWorldResponse> HelloWorldAsync(WindowsFormsApplicationTema2.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/modificare", ReplyAction="*")]
        void modificare(int trofeu, int cod);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/modificare", ReplyAction="*")]
        System.Threading.Tasks.Task modificareAsync(int trofeu, int cod);
        
        // CODEGEN: Generating message contract since element name nume_echipa from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/adaugare", ReplyAction="*")]
        WindowsFormsApplicationTema2.ServiceReference1.adaugareResponse adaugare(WindowsFormsApplicationTema2.ServiceReference1.adaugareRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/adaugare", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApplicationTema2.ServiceReference1.adaugareResponse> adaugareAsync(WindowsFormsApplicationTema2.ServiceReference1.adaugareRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/stergere", ReplyAction="*")]
        void stergere(int cod);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/stergere", ReplyAction="*")]
        System.Threading.Tasks.Task stergereAsync(int cod);
        
        // CODEGEN: Generating message contract since element name position from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/modificare_jucatori", ReplyAction="*")]
        WindowsFormsApplicationTema2.ServiceReference1.modificare_jucatoriResponse modificare_jucatori(WindowsFormsApplicationTema2.ServiceReference1.modificare_jucatoriRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/modificare_jucatori", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApplicationTema2.ServiceReference1.modificare_jucatoriResponse> modificare_jucatoriAsync(WindowsFormsApplicationTema2.ServiceReference1.modificare_jucatoriRequest request);
        
        // CODEGEN: Generating message contract since element name numeJucator from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/adaugare_jucatori", ReplyAction="*")]
        WindowsFormsApplicationTema2.ServiceReference1.adaugare_jucatoriResponse adaugare_jucatori(WindowsFormsApplicationTema2.ServiceReference1.adaugare_jucatoriRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/adaugare_jucatori", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApplicationTema2.ServiceReference1.adaugare_jucatoriResponse> adaugare_jucatoriAsync(WindowsFormsApplicationTema2.ServiceReference1.adaugare_jucatoriRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/stergere_jucatori", ReplyAction="*")]
        void stergere_jucatori(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/stergere_jucatori", ReplyAction="*")]
        System.Threading.Tasks.Task stergere_jucatoriAsync(int id);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApplicationTema2.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(WindowsFormsApplicationTema2.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApplicationTema2.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(WindowsFormsApplicationTema2.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class adaugareRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="adaugare", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApplicationTema2.ServiceReference1.adaugareRequestBody Body;
        
        public adaugareRequest() {
        }
        
        public adaugareRequest(WindowsFormsApplicationTema2.ServiceReference1.adaugareRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class adaugareRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nume_echipa;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string stadion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string city;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int trofeu;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int code;
        
        public adaugareRequestBody() {
        }
        
        public adaugareRequestBody(int id, string nume_echipa, string stadion, string city, int trofeu, int code) {
            this.id = id;
            this.nume_echipa = nume_echipa;
            this.stadion = stadion;
            this.city = city;
            this.trofeu = trofeu;
            this.code = code;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class adaugareResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="adaugareResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApplicationTema2.ServiceReference1.adaugareResponseBody Body;
        
        public adaugareResponse() {
        }
        
        public adaugareResponse(WindowsFormsApplicationTema2.ServiceReference1.adaugareResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class adaugareResponseBody {
        
        public adaugareResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class modificare_jucatoriRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="modificare_jucatori", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApplicationTema2.ServiceReference1.modificare_jucatoriRequestBody Body;
        
        public modificare_jucatoriRequest() {
        }
        
        public modificare_jucatoriRequest(WindowsFormsApplicationTema2.ServiceReference1.modificare_jucatoriRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class modificare_jucatoriRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string position;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int cod;
        
        public modificare_jucatoriRequestBody() {
        }
        
        public modificare_jucatoriRequestBody(string position, int id, int cod) {
            this.position = position;
            this.id = id;
            this.cod = cod;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class modificare_jucatoriResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="modificare_jucatoriResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApplicationTema2.ServiceReference1.modificare_jucatoriResponseBody Body;
        
        public modificare_jucatoriResponse() {
        }
        
        public modificare_jucatoriResponse(WindowsFormsApplicationTema2.ServiceReference1.modificare_jucatoriResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class modificare_jucatoriResponseBody {
        
        public modificare_jucatoriResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class adaugare_jucatoriRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="adaugare_jucatori", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApplicationTema2.ServiceReference1.adaugare_jucatoriRequestBody Body;
        
        public adaugare_jucatoriRequest() {
        }
        
        public adaugare_jucatoriRequest(WindowsFormsApplicationTema2.ServiceReference1.adaugare_jucatoriRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class adaugare_jucatoriRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string numeJucator;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string country;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string position;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int cod;
        
        public adaugare_jucatoriRequestBody() {
        }
        
        public adaugare_jucatoriRequestBody(int id, string numeJucator, string country, string position, int cod) {
            this.id = id;
            this.numeJucator = numeJucator;
            this.country = country;
            this.position = position;
            this.cod = cod;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class adaugare_jucatoriResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="adaugare_jucatoriResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApplicationTema2.ServiceReference1.adaugare_jucatoriResponseBody Body;
        
        public adaugare_jucatoriResponse() {
        }
        
        public adaugare_jucatoriResponse(WindowsFormsApplicationTema2.ServiceReference1.adaugare_jucatoriResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class adaugare_jucatoriResponseBody {
        
        public adaugare_jucatoriResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceTema2SoapChannel : WindowsFormsApplicationTema2.ServiceReference1.WebServiceTema2Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceTema2SoapClient : System.ServiceModel.ClientBase<WindowsFormsApplicationTema2.ServiceReference1.WebServiceTema2Soap>, WindowsFormsApplicationTema2.ServiceReference1.WebServiceTema2Soap {
        
        public WebServiceTema2SoapClient() {
        }
        
        public WebServiceTema2SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceTema2SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceTema2SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceTema2SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApplicationTema2.ServiceReference1.HelloWorldResponse WindowsFormsApplicationTema2.ServiceReference1.WebServiceTema2Soap.HelloWorld(WindowsFormsApplicationTema2.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            WindowsFormsApplicationTema2.ServiceReference1.HelloWorldRequest inValue = new WindowsFormsApplicationTema2.ServiceReference1.HelloWorldRequest();
            inValue.Body = new WindowsFormsApplicationTema2.ServiceReference1.HelloWorldRequestBody();
            WindowsFormsApplicationTema2.ServiceReference1.HelloWorldResponse retVal = ((WindowsFormsApplicationTema2.ServiceReference1.WebServiceTema2Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApplicationTema2.ServiceReference1.HelloWorldResponse> WindowsFormsApplicationTema2.ServiceReference1.WebServiceTema2Soap.HelloWorldAsync(WindowsFormsApplicationTema2.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApplicationTema2.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            WindowsFormsApplicationTema2.ServiceReference1.HelloWorldRequest inValue = new WindowsFormsApplicationTema2.ServiceReference1.HelloWorldRequest();
            inValue.Body = new WindowsFormsApplicationTema2.ServiceReference1.HelloWorldRequestBody();
            return ((WindowsFormsApplicationTema2.ServiceReference1.WebServiceTema2Soap)(this)).HelloWorldAsync(inValue);
        }
        
        public void modificare(int trofeu, int cod) {
            base.Channel.modificare(trofeu, cod);
        }
        
        public System.Threading.Tasks.Task modificareAsync(int trofeu, int cod) {
            return base.Channel.modificareAsync(trofeu, cod);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApplicationTema2.ServiceReference1.adaugareResponse WindowsFormsApplicationTema2.ServiceReference1.WebServiceTema2Soap.adaugare(WindowsFormsApplicationTema2.ServiceReference1.adaugareRequest request) {
            return base.Channel.adaugare(request);
        }
        
        public void adaugare(int id, string nume_echipa, string stadion, string city, int trofeu, int code) {
            WindowsFormsApplicationTema2.ServiceReference1.adaugareRequest inValue = new WindowsFormsApplicationTema2.ServiceReference1.adaugareRequest();
            inValue.Body = new WindowsFormsApplicationTema2.ServiceReference1.adaugareRequestBody();
            inValue.Body.id = id;
            inValue.Body.nume_echipa = nume_echipa;
            inValue.Body.stadion = stadion;
            inValue.Body.city = city;
            inValue.Body.trofeu = trofeu;
            inValue.Body.code = code;
            WindowsFormsApplicationTema2.ServiceReference1.adaugareResponse retVal = ((WindowsFormsApplicationTema2.ServiceReference1.WebServiceTema2Soap)(this)).adaugare(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApplicationTema2.ServiceReference1.adaugareResponse> WindowsFormsApplicationTema2.ServiceReference1.WebServiceTema2Soap.adaugareAsync(WindowsFormsApplicationTema2.ServiceReference1.adaugareRequest request) {
            return base.Channel.adaugareAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApplicationTema2.ServiceReference1.adaugareResponse> adaugareAsync(int id, string nume_echipa, string stadion, string city, int trofeu, int code) {
            WindowsFormsApplicationTema2.ServiceReference1.adaugareRequest inValue = new WindowsFormsApplicationTema2.ServiceReference1.adaugareRequest();
            inValue.Body = new WindowsFormsApplicationTema2.ServiceReference1.adaugareRequestBody();
            inValue.Body.id = id;
            inValue.Body.nume_echipa = nume_echipa;
            inValue.Body.stadion = stadion;
            inValue.Body.city = city;
            inValue.Body.trofeu = trofeu;
            inValue.Body.code = code;
            return ((WindowsFormsApplicationTema2.ServiceReference1.WebServiceTema2Soap)(this)).adaugareAsync(inValue);
        }
        
        public void stergere(int cod) {
            base.Channel.stergere(cod);
        }
        
        public System.Threading.Tasks.Task stergereAsync(int cod) {
            return base.Channel.stergereAsync(cod);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApplicationTema2.ServiceReference1.modificare_jucatoriResponse WindowsFormsApplicationTema2.ServiceReference1.WebServiceTema2Soap.modificare_jucatori(WindowsFormsApplicationTema2.ServiceReference1.modificare_jucatoriRequest request) {
            return base.Channel.modificare_jucatori(request);
        }
        
        public void modificare_jucatori(string position, int id, int cod) {
            WindowsFormsApplicationTema2.ServiceReference1.modificare_jucatoriRequest inValue = new WindowsFormsApplicationTema2.ServiceReference1.modificare_jucatoriRequest();
            inValue.Body = new WindowsFormsApplicationTema2.ServiceReference1.modificare_jucatoriRequestBody();
            inValue.Body.position = position;
            inValue.Body.id = id;
            inValue.Body.cod = cod;
            WindowsFormsApplicationTema2.ServiceReference1.modificare_jucatoriResponse retVal = ((WindowsFormsApplicationTema2.ServiceReference1.WebServiceTema2Soap)(this)).modificare_jucatori(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApplicationTema2.ServiceReference1.modificare_jucatoriResponse> WindowsFormsApplicationTema2.ServiceReference1.WebServiceTema2Soap.modificare_jucatoriAsync(WindowsFormsApplicationTema2.ServiceReference1.modificare_jucatoriRequest request) {
            return base.Channel.modificare_jucatoriAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApplicationTema2.ServiceReference1.modificare_jucatoriResponse> modificare_jucatoriAsync(string position, int id, int cod) {
            WindowsFormsApplicationTema2.ServiceReference1.modificare_jucatoriRequest inValue = new WindowsFormsApplicationTema2.ServiceReference1.modificare_jucatoriRequest();
            inValue.Body = new WindowsFormsApplicationTema2.ServiceReference1.modificare_jucatoriRequestBody();
            inValue.Body.position = position;
            inValue.Body.id = id;
            inValue.Body.cod = cod;
            return ((WindowsFormsApplicationTema2.ServiceReference1.WebServiceTema2Soap)(this)).modificare_jucatoriAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApplicationTema2.ServiceReference1.adaugare_jucatoriResponse WindowsFormsApplicationTema2.ServiceReference1.WebServiceTema2Soap.adaugare_jucatori(WindowsFormsApplicationTema2.ServiceReference1.adaugare_jucatoriRequest request) {
            return base.Channel.adaugare_jucatori(request);
        }
        
        public void adaugare_jucatori(int id, string numeJucator, string country, string position, int cod) {
            WindowsFormsApplicationTema2.ServiceReference1.adaugare_jucatoriRequest inValue = new WindowsFormsApplicationTema2.ServiceReference1.adaugare_jucatoriRequest();
            inValue.Body = new WindowsFormsApplicationTema2.ServiceReference1.adaugare_jucatoriRequestBody();
            inValue.Body.id = id;
            inValue.Body.numeJucator = numeJucator;
            inValue.Body.country = country;
            inValue.Body.position = position;
            inValue.Body.cod = cod;
            WindowsFormsApplicationTema2.ServiceReference1.adaugare_jucatoriResponse retVal = ((WindowsFormsApplicationTema2.ServiceReference1.WebServiceTema2Soap)(this)).adaugare_jucatori(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApplicationTema2.ServiceReference1.adaugare_jucatoriResponse> WindowsFormsApplicationTema2.ServiceReference1.WebServiceTema2Soap.adaugare_jucatoriAsync(WindowsFormsApplicationTema2.ServiceReference1.adaugare_jucatoriRequest request) {
            return base.Channel.adaugare_jucatoriAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApplicationTema2.ServiceReference1.adaugare_jucatoriResponse> adaugare_jucatoriAsync(int id, string numeJucator, string country, string position, int cod) {
            WindowsFormsApplicationTema2.ServiceReference1.adaugare_jucatoriRequest inValue = new WindowsFormsApplicationTema2.ServiceReference1.adaugare_jucatoriRequest();
            inValue.Body = new WindowsFormsApplicationTema2.ServiceReference1.adaugare_jucatoriRequestBody();
            inValue.Body.id = id;
            inValue.Body.numeJucator = numeJucator;
            inValue.Body.country = country;
            inValue.Body.position = position;
            inValue.Body.cod = cod;
            return ((WindowsFormsApplicationTema2.ServiceReference1.WebServiceTema2Soap)(this)).adaugare_jucatoriAsync(inValue);
        }
        
        public void stergere_jucatori(int id) {
            base.Channel.stergere_jucatori(id);
        }
        
        public System.Threading.Tasks.Task stergere_jucatoriAsync(int id) {
            return base.Channel.stergere_jucatoriAsync(id);
        }
    }
}
